### ISSUE TITLE
Above 180% Zoom with approval on document prevents accessing details tab content (activity, sharing...)

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/approval#34]
See bottom right of the pictures.

![22-07-18_000016](https://user-images.githubusercontent.com/87175513/179562916-86f81954-2b83-48fd-99d7-a29f89c309cb.png)
![22-07-18_000017](https://user-images.githubusercontent.com/87175513/179562923-074e8b74-6f59-4187-b0eb-ae8bca2cbfe7.png)

From an accessibility point of view, this is a problem for people in need of zooming to read.

**Comment by eneiluj** [comment]
Hi, thanks for the issue. I think this is more a sidebar style issue than an approval app issue. At some zoom level, even without approval buttons/details, tabs will get hidden and we can't scroll down.

Also, keep in mind that non-admin users won't see the tag selector because hidden tags are only shown to admins. That saves some space.

What do you think?

**Comment by eneiluj** [comment]
> should I tranfer the issue to server repo ?

Yes if you think zooming more than 180% can happen then it deserves an issue in server.

About the tag, I agree with you. I just wanted to underline that the tag selector is not related with the approval app and that it's less likely to see it when you're not an admin.

Feel free to reopen the issue if needed.
