### ISSUE TITLE
multible persons approval

### ISSUE THREAD

**Issue by MrManor** [nextcloud/approval#49]
In some organizations/associations, not just one -but all members of the board must approve the minutes before they can be published. 

One for the wish list: if one could write the minutes and when all members of the board has approved it, it would trigger a secondary flow which converted to pdf and place the result in a public folder.

**Comment by IAmDarthMole** [comment]
I'm still familiarizing myself with the workflow approvals in Nextcloud so this is perhaps convoluted or just not viable but would the following workaround be sufficient?

## Uses
Approval workflows plugin
Automated PDF conversion
System Tags from Approval workflows plugin

## Process
### Approval workflows plugin
Create a workflow for each board member in the Approval workflows plugin. 13 board members = 13 separate workflows unfortunately. 
#### 1st Workflow
1. Set the "Tag to act on" as something like MeetingMinsApproval-Start (or MMA-Start, First approver'sname-Pending, First-Approval, etc.).
2. Set "Who can request approval" as the author(s) of the meeting minutes (individually or a group) 
3. Set "Who can approve" as a **single** member of the board. Choose based on seniority, first name alphabetical, last name alphabetical, doesn't matter.
4. Set "Tag set on approval" as the tag used in "Tag to act on" in 2nd Workflow below. **This chains the workflows together)**
5. Set "Tag set on rejection" as "<Tag to act on>-Rejected" (IE: If you used First-Approval above use First-Approval-Rejected)

#### 2nd Workflow
1. Set the "Tag to act on" as something like MMA-Second, Second approver'sname-Pending, Second-Approval, etc.).
2. Set "Who can request approval" as the author(s) of the meeting minutes (individually or a group) 
3. Set "Who can approve" as the **next** member of the board based on your chosen hierarchy (ie: seniority, first name alphabetical, last name alphabetical)
4. Set "Tag set on approval" as the tag used in "Tag to act on" in 3rd Workflow below.
5. Set "Tag set on rejection" as "<Tag to act on>-Rejected" (IE: If you used Second-Approval above use Second-Approval-Rejected)

#### 3rd Workflow and up to _second to last workflow_
Repeat the above steps for all following board members, being sure to update Step 4's "Tag set on approval" with the next workflow's "Tag to act on" (Step 1) to ensure they properly chain together.

#### Last Workflow (Last Board Member)
1. Set the "Tag to act on" as something like MMA-Last, Last approver'sname-Pending, Last-Approval, etc.).
2. Set "Who can request approval" as the author(s) of the meeting minutes (individually or a group) 
3. Set "Who can approve" as the **last** member of the board based on your chosen hierarchy (ie: seniority, first name alphabetical, last name alphabetical)
4. Set "Tag set on approval" as something like MMA-Approved, All-Approved, etc. (Only make this change in Step 4 on the **last** workflow.)
5. Set "Tag set on rejection" as "<Tag to act on>-Rejected" (IE: If you used Last-Approval above use Second-Approval-Rejected)

### Automated PDF Conversion plugin
Only need one workflow here.

1. Set "When" to "Tag Assigned"
2. Set "and" to "File system tag"
3. Set argument to "is tagged with"
4. Set "Select a tag" to "Tag set on approval" from Step 4 above in the **Last Workflow** 
5. Set PDF conversion to desired option

## Caveats 
1. The number of board members may make this workaround too convoluted.
2. If at anytime someone rejects the document on their turn, it would have to be started again from the beginning.
3. The workflows are chained together, therefor if one person takes two days to review the document and approve it then the flow has to wait two days.
4. I was personally unable to get the pdf conversion to work. I'm not sure if this is a bug or if something is wrong with my install. The above settings, from my understanding, should work, though the trigger may need to be tweaked. 

Not sure if you already thought of the above but I hope this helped your situation! I do agree that having "multiple users" or "all members of a group" requirement for approvals built in will certainly be easier.

**Comment by MrManor** [comment]
Thanks for your idea, although I think that I will have to read it a couple of times more, before I can fully grasp all the mechanics involved. Using tags like suggested might be the key for solving this problem, maybe in the future tags can be used for other variations, like: if more than half the board members accepts, do ... 

Also I see the same limitations as you mention, except number 2. If anyone rejects the minutes and requests a rewrite, surely all board members must review the new version.

**Comment by IAmDarthMole** [comment]
You're welcome, and my apologies if the details were, well, too detailed lol. I'm including images below to hopefully clean up/clarify the process. 

Regarding 2, it was more related to the process. As in the approval flow wouldn't restart automatically once the changes were made. 

Regarding the below images. I will be utilizing the following names for the board in the order they are listed (assumed hierarchy).

1. James Bethren
2. Sophia Gimble
3. Jack Smith
4. Beth Kittle

The group "Transcribers" is for the meeting minute writers.

![image](https://github.com/nextcloud/approval/assets/42397503/60d67a1b-f5a4-49c5-b7bd-d2ef833ac92c)



Once the flow reaches Beth Kittle, the last board member, it stops and then the PDF conversion flow kicks in due to the below settings. The PDF conversion workflow is looking for the MM-BK-Approved tag, which only comes into play when you finish the Meeting Minute Approval workflow chain.


![image](https://github.com/nextcloud/approval/assets/42397503/9dede2e1-d571-4b45-9470-b78dd2470261)


## Alternatively

As I was working on this reply I also realized an alternative process that may be a little less convoluted. 

You will only have 1 approval option per Board Member which will still be handled by tags.

MM-JB-Approved
MM-SG-Approved
MM-JS-Approved
MM-BK-Approved

Your board members will approve the meeting minutes by adding their corresponding tag to the document (shown below). The control/auditing is that the activity will show who applied which tag.

![image](https://github.com/nextcloud/approval/assets/42397503/2fe8df9d-4a75-4168-b466-1b07d01751ec)


The PDF Conversion flow will be looking for all four tags to trigger the pdf creation (shown below).

![image](https://github.com/nextcloud/approval/assets/42397503/74ceba9f-d1da-4ce1-847c-2fe6480a0470)

Hope all the above helped a bit more! Or at least didn't make things worse :)

**Comment by MrManor** [comment]
I get the first solution now, thanks to the detailed explanation  :-)  But as you also state in you first post, the long chain of serial interactions makes the overall solution susceptible to delays.
I think I try to follow the path of the alternative solution solution. I like the idea and that the board members can all get the chance to approve the minutes as soon as it is written, - while still having the meeting fresh in memory.

I guess a bonus from using tags pr person is, that it is possible later to pull a list of all documents one person has signed.

I'll close the request for now, while I try to implement it (currently struggling with the pdf conversion to) as it seems that is actually possible using the current NC-flow.
